[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://akt.waw.pl/*"
  to = "https://www.akt.waw.pl/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://akt-waw.netlify.app/*"
  to = "https://www.akt.waw.pl/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://main--akt-waw.netlify.app/*"
  to = "https://www.akt.waw.pl/:splat"
  status = 301
  force = true